### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by aelharda** [J-BarrettPY/AutoNMAP#1]
Can you update the readme with steps and line to modify?
I get errors in the discord portion which i don't really need.

`Scanning 192.168.1.12
Exception in thread Thread-1 (run_nmap):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/anasrocks/AutoNMAP/AutoNMAP-PROJECT/RaspberryPi/NMAP-AUTO-rasppi.py", line 156, in run_nmap
    upload_to_discord(filename, url, result.stdout)
  File "/home/anasrocks/AutoNMAP/AutoNMAP-PROJECT/RaspberryPi/NMAP-AUTO-rasppi.py", line 253, in upload_to_discord
    write_to_mongodb(level, json_data,
  File "/home/anasrocks/AutoNMAP/AutoNMAP-PROJECT/RaspberryPi/NMAP-AUTO-rasppi.py", line 79, in write_to_mongodb
    collection.insert_one(data)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/collection.py", line 669, in insert_one
    self._insert_one(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1522, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1840, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1823, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1766, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 573, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 589, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65aabd4a9dbeb00bb421f925, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
`

**Comment by JB-ps1** [comment]
Dear friend,

Thank you for your interest in Auto NMAP. I will take a look at the discord
integration and not force users to use it by parsing the option. However,
the error you are receiving seems to be related to MongoDB which Auto NMAP
uses to collect data on a local server. If you haven't already, please
verify your configuration for MongoDB client and server.

Regards,

Jacob
